[install]
# Configure package manager settings
cache = true
exact = false
production = false

[install.scopes]
# Allow packages from any scope

[install.lockfile]
# Save lockfile in project root
save = true
print = "yarn"
